"""empty message

Revision ID: 62ea444d5931
Revises: 5a6853efda97
Create Date: 2023-08-07 15:21:07.812020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ea444d5931'
down_revision = '5a6853efda97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=250), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('created', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=250), nullable=False),
    sa.Column('status_change', sa.Date(), nullable=False),
    sa.Column('open_actions', sa.String(length=250), nullable=False),
    sa.Column('total_actions', sa.String(length=250), nullable=False),
    sa.Column('association', sa.String(length=250), nullable=False),
    sa.Column('overdue', sa.String(length=250), nullable=False),
    sa.Column('images', sa.String(length=250), nullable=False),
    sa.Column('comments', sa.String(length=250), nullable=False),
    sa.Column('documents', sa.String(length=250), nullable=False),
    sa.Column('project', sa.String(length=250), nullable=False),
    sa.Column('report_forms_status', sa.String(length=250), nullable=False),
    sa.Column('report_forms_group', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Source')
    # ### end Alembic commands ###
