"""empty message

Revision ID: 728d02052610
Revises: ce7e088301ad
Create Date: 2023-08-08 11:37:44.201274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728d02052610'
down_revision = 'ce7e088301ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=250), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('created', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=250), nullable=False),
    sa.Column('status_change', sa.String(), nullable=False),
    sa.Column('open_actions', sa.String(length=250), nullable=False),
    sa.Column('total_actions', sa.String(length=250), nullable=False),
    sa.Column('association', sa.String(length=250), nullable=False),
    sa.Column('overdue', sa.String(length=250), nullable=False),
    sa.Column('images', sa.String(length=250), nullable=False),
    sa.Column('comments', sa.String(length=250), nullable=False),
    sa.Column('documents', sa.String(length=250), nullable=False),
    sa.Column('project', sa.String(length=250), nullable=False),
    sa.Column('report_forms_status', sa.String(length=250), nullable=False),
    sa.Column('report_forms_group', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Source')
    # ### end Alembic commands ###
